(() => {
"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$("#stage"),ctx=canvas.getContext("2d");
const state={projectName:"whiteboard-ai-project",cues:[],scenes:[],sceneIndex:-1,elementIndex:-1,timeMs:0,playing:false,projectPlaying:false,drawMode:false,dragStart:null,draftRect:null,raf:null,lastTick:0,generatedImageData:null,mediaFile:null,mediaDuration:0};
const defaults={models:{openai:{text:"gpt-5.6",image:"gpt-image-2"},gemini:{text:"gemini-3.6-flash",image:"gemini-3.1-flash-image"},anthropic:{text:"claude-sonnet-5",image:""},xai:{text:"grok-4.5",image:"grok-imagine-image-quality"}}};
const currentScene=()=>state.scenes[state.sceneIndex]||null,currentElement=()=>currentScene()?.elements?.[state.elementIndex]||null,paper=()=>$("#paperColor").value||"#f5ebd7";
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1800)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function clamp(n,a,b){return Math.min(b,Math.max(a,n))}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function msToSrt(ms){ms=Math.max(0,Math.round(ms));const h=Math.floor(ms/3600000);ms%=3600000;const m=Math.floor(ms/60000);ms%=60000;const s=Math.floor(ms/1000),x=ms%1000;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")},${String(x).padStart(3,"0")}`}
function parseTime(v){const m=v.trim().match(/(\d+):(\d+):(\d+)[,.](\d+)/);if(!m)return 0;return((+m[1]*3600 + +m[2]*60 + +m[3])*1000)+ +String(m[4]).padEnd(3,"0").slice(0,3)}
function parseSRT(text){text=extractSrt(text).replace(/\r/g,"").trim();if(!text)return[];return text.split(/\n{2,}/).map((block,i)=>{const lines=block.split("\n");const ti=lines.findIndex(x=>x.includes("-->"));if(ti<0)return null;const [a,b]=lines[ti].split("-->").map(x=>x.trim());const txt=lines.slice(ti+1).join(" ").replace(/<[^>]+>/g,"").trim();return{id:i+1,startMs:parseTime(a),endMs:parseTime(b),text:txt}}).filter(Boolean).sort((a,b)=>a.startMs-b.startMs)}
function cuesToSrt(cues){return cues.map((c,i)=>`${i+1}\n${msToSrt(c.startMs)} --> ${msToSrt(c.endMs)}\n${c.text}`).join("\n\n")}
function extractSrt(text){const fence=String(text||"").match(/```(?:srt)?\s*([\s\S]*?)```/i);return(fence?fence[1]:String(text||"")).trim()}
function splitText(text,maxChars){const clean=String(text||"").replace(/\r/g,"").replace(/[ \t]+/g," ").trim();if(!clean)return[];let units=clean.split(/(?<=[.!?。！？]|[다요죠]\.)\s+|\n+/).map(x=>x.trim()).filter(Boolean);if(units.length===1)units=clean.split(/(?<=[.!?。！？])|\n+/).map(x=>x.trim()).filter(Boolean);const out=[];for(const u of units){if(u.length<=maxChars){out.push(u);continue}let rest=u;while(rest.length>maxChars){let cut=rest.lastIndexOf(" ",maxChars);if(cut<Math.floor(maxChars*.55))cut=maxChars;out.push(rest.slice(0,cut).trim());rest=rest.slice(cut).trim()}if(rest)out.push(rest)}return out}
function localSrtFromText(text,totalDuration=0){const maxChars=+$("#captionChars").value||28,minSec=+$("#captionMinSec").value||1.3,maxSec=+$("#captionMaxSec").value||4.5,cps=+$("#charsPerSec").value||7.5;const chunks=splitText(text,maxChars);let durations=chunks.map(t=>clamp(t.replace(/\s/g,"").length/cps,minSec,maxSec)*1000);if(totalDuration>0&&durations.length){const natural=durations.reduce((a,b)=>a+b,0);const scale=totalDuration*1000/natural;durations=durations.map(d=>clamp(d*scale,minSec*1000,maxSec*1000));const sum=durations.reduce((a,b)=>a+b,0);if(sum>0){const finalScale=totalDuration*1000/sum;durations=durations.map(d=>d*finalScale)}}let t=0;const cues=chunks.map((txt,i)=>{const st=t,en=t+durations[i];t=en;return{id:i+1,startMs:st,endMs:en,text:txt}});return cuesToSrt(cues)}
function validateSrt(text){const cues=parseSRT(text),issues=[];if(!cues.length)return{ok:false,issues:["유효한 SRT 블록을 찾지 못했습니다."],cues:[]};for(let i=0;i<cues.length;i++){const c=cues[i];if(c.endMs<=c.startMs)issues.push(`${i+1}번: 종료 시간이 시작보다 빠릅니다.`);if(c.endMs-c.startMs<450)issues.push(`${i+1}번: 표시 시간이 0.45초보다 짧습니다.`);if(i&&c.startMs<cues[i-1].endMs)issues.push(`${i+1}번: 이전 자막과 시간이 겹칩니다.`);if(!c.text)issues.push(`${i+1}번: 자막 텍스트가 비었습니다.`)}return{ok:!issues.length,issues,cues}}
function normalizeSrt(text){const cues=parseSRT(text);let prev=0;for(const c of cues){c.startMs=Math.max(prev,c.startMs);c.endMs=Math.max(c.startMs+500,c.endMs);prev=c.endMs}return cuesToSrt(cues)}
function makeScene(cues,idx){const base=cues[0]?.startMs||0,local=cues.map(c=>({...c,startMs:c.startMs-base,endMs:c.endMs-base}));return{id:`scene-${String(idx+1).padStart(2,"0")}`,title:local[0]?.text?.slice(0,32)||`장면 ${idx+1}`,durationMs:Math.max(3000,local.at(-1)?.endMs||5000),cues:local,imageData:null,imageName:"",imageWidth:1280,imageHeight:720,elements:[],prompt:""}}
function splitScenes(cues,targetSec,gapSec){if(!cues.length)return[];const target=targetSec*1000,slack=gapSec*1000,out=[];let batch=[],start=cues[0].startMs;for(const cue of cues){if(batch.length&&cue.endMs-start>target+slack){out.push(makeScene(batch,out.length));batch=[];start=cue.startMs}batch.push(cue);if(batch.length>1&&cue.endMs-start>=Math.max(5000,target-slack)){out.push(makeScene(batch,out.length));batch=[];start=cue.endMs}}if(batch.length)out.push(makeScene(batch,out.length));return out}
function renumberScenes(){state.scenes.forEach((s,i)=>s.id=`scene-${String(i+1).padStart(2,"0")}`)}
function buildScenesFromSrt(text){const cues=parseSRT(text);if(!cues.length){toast("유효한 SRT가 없습니다.");return false}state.cues=cues;state.scenes=splitScenes(cues,+$("#targetSec").value||25,+$("#sceneGap").value||5);selectScene(0);renderPromptSceneList();return true}

function renderSceneList(){const h=$("#sceneList");h.innerHTML="";state.scenes.forEach((s,i)=>{const e=document.createElement("div");e.className="scene-item"+(i===state.sceneIndex?" active":"");e.innerHTML=`<strong>${esc(s.id)} · ${esc(s.title)}</strong><small>${(s.durationMs/1000).toFixed(1)}초 · 자막 ${s.cues.length} · 요소 ${s.elements.length}${s.imageData?" · 이미지 ✓":""}</small><div class="scene-actions"><button data-a="dup">복제</button><button data-a="del">삭제</button></div>`;e.onclick=ev=>{const a=ev.target.dataset.a;if(a==="del"){ev.stopPropagation();state.scenes.splice(i,1);renumberScenes();selectScene(Math.min(i,state.scenes.length-1));renderPromptSceneList();return}if(a==="dup"){ev.stopPropagation();const c=JSON.parse(JSON.stringify(s));state.scenes.splice(i+1,0,c);renumberScenes();selectScene(i+1);renderPromptSceneList();return}selectScene(i)};h.appendChild(e)})}
function renderPromptSceneList(){const h=$("#promptSceneList");h.innerHTML="";state.scenes.forEach((s,i)=>{const e=document.createElement("div");e.className="scene-item"+(i===state.sceneIndex?" active":"");e.innerHTML=`<strong>${esc(s.id)} · ${esc(s.title)}</strong><small>${s.prompt?"프롬프트 ✓":"프롬프트 미생성"}${s.imageData?" · 이미지 ✓":""}</small>`;e.onclick=()=>{selectScene(i);syncPromptEditor();showTab("prompt")};h.appendChild(e)})}
function renderElementList(){const s=currentScene(),h=$("#elementList");h.innerHTML="";if(!s)return;s.elements.forEach((e,i)=>{const row=document.createElement("div");row.className="element-item"+(i===state.elementIndex?" active":"");row.innerHTML=`<strong>${i+1}. ${esc(e.label||e.id)}</strong><small>${e.reveal.startMs}ms + ${e.reveal.durationMs}ms · ${esc(e.subtitle||"")}</small>`;row.onclick=()=>{state.elementIndex=i;updateInspector();renderElementList();draw()};h.appendChild(row)})}
function updateInspector(){const e=currentElement(),s=currentScene();$("#elementInspector").classList.toggle("hidden",!e);const sel=$("#elSubtitle");sel.innerHTML="";(s?.cues||[]).forEach((c,i)=>{const o=document.createElement("option");o.value=i;o.textContent=`${i+1}. ${c.text}`;sel.appendChild(o)});if(!e)return;$("#elLabel").value=e.label||"";$("#elRole").value=e.narrativeRole||"";$("#elSubtitle").value=Math.max(0,(s?.cues||[]).findIndex(c=>c.text===e.subtitle));$("#elStart").value=e.reveal.startMs;$("#elDuration").value=e.reveal.durationMs;$("#elDirection").value=e.reveal.direction;$("#elPadding").value=e.reveal.maskPaddingPx||0;$("#elColorPhase").value=e.colorPhase??72}
function selectScene(i){state.sceneIndex=i>=0&&i<state.scenes.length?i:-1;state.elementIndex=-1;state.timeMs=0;stopPlayback();renderSceneList();renderElementList();renderPromptSceneList();updateInspector();$("#scrubber").value=0;updateCanvasSize();draw();syncPromptEditor()}
function updateCanvasSize(){canvas.width=+$("#outWidth").value||1280;canvas.height=+$("#outHeight").value||720}
function fileToDataURL(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
async function ensureSceneImage(s){if(s?.imageData&&!s._img){try{s._img=await loadImage(s.imageData)}catch{}}return s?._img}
async function setSceneImageData(data,name="generated.png"){const s=currentScene();if(!s){toast("먼저 장면을 선택하세요.");return}const img=await loadImage(data);s.imageData=data;s.imageName=name;s.imageWidth=img.naturalWidth;s.imageHeight=img.naturalHeight;s._img=img;if($("#autoFullElement").checked&&!s.elements.length)addFullRegion();renderSceneList();renderPromptSceneList();draw();toast("현재 장면에 이미지를 적용했습니다.")}
async function loadImageFile(f){await setSceneImageData(await fileToDataURL(f),f.name)}
function addFullRegion(){const s=currentScene();if(!s||!s.imageData)return;const idx=s.elements.length,cue=s.cues[0],dur=Math.max(800,s.durationMs-200);s.elements.push({id:`element-${idx+1}`,label:idx?`전체 이미지 ${idx+1}`:"전체 이미지",sequence:idx+1,narrativeRole:"scene",subtitle:cue?.text||"",type:"illustration",region:{x:0,y:0,width:s.imageWidth,height:s.imageHeight},reveal:{direction:"left_to_right",startMs:0,durationMs:dur,maskPaddingPx:0,protectedRegions:[]},handPath:{start:[0,Math.round(s.imageHeight/2)],end:[s.imageWidth,Math.round(s.imageHeight/2)],easing:"easeInOut"},colorPhase:72});state.elementIndex=s.elements.length-1;renderElementList();updateInspector();renderSceneList();draw()}
function imageTransform(s,img){const cw=canvas.width,ch=canvas.height,iw=img.naturalWidth,ih=img.naturalHeight,scale=Math.min(cw/iw,ch/ih);return{scale,x:(cw-iw*scale)/2,y:(ch-ih*scale)/2,w:iw*scale,h:ih*scale}}
function progressFor(e,t){if(t<=e.reveal.startMs)return 0;if(t>=e.reveal.startMs+e.reveal.durationMs)return 1;return(t-e.reveal.startMs)/e.reveal.durationMs}
function revealRect(r,p,d){let{x,y,width:w,height:h}=r;if(d==="right_to_left")return{x:x+w*(1-p),y,w:w*p,h};if(d==="top_to_bottom")return{x,y,w,h:h*p};if(d==="bottom_to_top")return{x,y:y+h*(1-p),w,h:h*p};if(d==="center_out"){const ww=w*p,hh=h*p;return{x:x+(w-ww)/2,y:y+(h-hh)/2,w:ww,h:hh}}return{x,y,w:w*p,h}}
function drawHand(rr,d,p){if(!rr||p<=0||p>=1)return;let x=rr.x+rr.w,y=rr.y+rr.h/2;if(d==="right_to_left"){x=rr.x;y=rr.y+rr.h/2}if(d==="top_to_bottom"){x=rr.x+rr.w/2;y=rr.y+rr.h}if(d==="bottom_to_top"){x=rr.x+rr.w/2;y=rr.y}if(d==="center_out"){x=rr.x+rr.w;y=rr.y+rr.h}ctx.save();ctx.translate(x,y);ctx.rotate(-.32);ctx.strokeStyle="#24201c";ctx.lineWidth=3;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(-32,18);ctx.lineTo(6,-15);ctx.stroke();ctx.fillStyle="#e9b99d";ctx.beginPath();ctx.arc(-35,20,8,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawSubtitle(s){if(!$("#burnSubtitles").checked)return;const cue=s?.cues.find(c=>state.timeMs>=c.startMs&&state.timeMs<c.endMs);if(!cue?.text)return;ctx.save();ctx.font=`600 ${Math.round(canvas.height*.032)}px system-ui`;const maxW=canvas.width*.82,pad=16;const words=cue.text.split(/\s+/),lines=[];let line="";for(const w of words){const test=line?line+" "+w:w;if(ctx.measureText(test).width>maxW&&line){lines.push(line);line=w}else line=test}if(line)lines.push(line);const lh=Math.round(canvas.height*.047),boxH=lines.length*lh+pad*1.25,y=canvas.height-boxH-Math.round(canvas.height*.035);ctx.fillStyle="rgba(20,20,20,.72)";ctx.fillRect(canvas.width*.08,y,canvas.width*.84,boxH);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="middle";lines.forEach((l,i)=>ctx.fillText(l,canvas.width/2,y+pad*.6+lh*(i+.5)));ctx.restore()}
async function draw(){const s=currentScene();ctx.save();ctx.fillStyle=paper();ctx.fillRect(0,0,canvas.width,canvas.height);if(!s?.imageData){ctx.restore();$("#emptyHint").classList.remove("hidden");updateTimeLabel();return}$("#emptyHint").classList.add("hidden");const img=await ensureSceneImage(s);if(!img){ctx.restore();return}const tr=imageTransform(s,img);if(!s.elements.length){ctx.globalAlpha=.2;ctx.drawImage(img,tr.x,tr.y,tr.w,tr.h);ctx.globalAlpha=1}else for(const e of s.elements){const p=progressFor(e,state.timeMs);if(p<=0)continue;const rr=revealRect(e.region,p,e.reveal.direction);ctx.save();ctx.beginPath();ctx.rect(tr.x+rr.x*tr.scale,tr.y+rr.y*tr.scale,rr.w*tr.scale,rr.h*tr.scale);ctx.clip();ctx.filter=p<(e.colorPhase??72)/100?"grayscale(1) contrast(1.35) brightness(.82)":"none";ctx.drawImage(img,tr.x,tr.y,tr.w,tr.h);ctx.restore();if((state.playing||state.projectPlaying)&&p>0&&p<1)drawHand({x:tr.x+rr.x*tr.scale,y:tr.y+rr.y*tr.scale,w:rr.w*tr.scale,h:rr.h*tr.scale},e.reveal.direction,p)}if(state.elementIndex>=0&&!state.playing&&!state.projectPlaying){const e=currentElement();if(e){ctx.save();ctx.strokeStyle="#1f5c4a";ctx.lineWidth=2;ctx.setLineDash([8,5]);ctx.strokeRect(tr.x+e.region.x*tr.scale,tr.y+e.region.y*tr.scale,e.region.width*tr.scale,e.region.height*tr.scale);ctx.restore()}}drawSubtitle(s);ctx.restore();updateTimeLabel()}
function updateTimeLabel(){const s=currentScene(),dur=(s?.durationMs||0)+ +$("#holdMs").value;$("#timeLabel").textContent=`${(state.timeMs/1000).toFixed(2)} / ${(dur/1000).toFixed(2)}s`;const cue=s?.cues.find(c=>state.timeMs>=c.startMs&&state.timeMs<c.endMs);$("#subtitleNow").textContent=cue?.text||"";if(dur>0)$("#scrubber").value=Math.round(clamp(state.timeMs/dur,0,1)*1000)}
function canvasPoint(ev){const r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*(canvas.width/r.width),y:(ev.clientY-r.top)*(canvas.height/r.height)}}
canvas.addEventListener("pointerdown",async e=>{if(!state.drawMode)return;const s=currentScene(),img=await ensureSceneImage(s);if(!s||!img)return;canvas.setPointerCapture(e.pointerId);state.dragStart=canvasPoint(e);state.draftRect={x:state.dragStart.x,y:state.dragStart.y,w:0,h:0};draw()});canvas.addEventListener("pointermove",e=>{if(!state.drawMode||!state.dragStart)return;const p=canvasPoint(e),a=state.dragStart;state.draftRect={x:Math.min(a.x,p.x),y:Math.min(a.y,p.y),w:Math.abs(p.x-a.x),h:Math.abs(p.y-a.y)};draw()});canvas.addEventListener("pointerup",async()=>{if(!state.drawMode||!state.dragStart)return;const s=currentScene(),img=await ensureSceneImage(s),tr=imageTransform(s,img),d=state.draftRect;state.dragStart=null;state.draftRect=null;state.drawMode=false;$("#addRegionBtn").textContent="영역 그리기";if(d.w<8||d.h<8){draw();return}const x=Math.max(0,(d.x-tr.x)/tr.scale),y=Math.max(0,(d.y-tr.y)/tr.scale),w=Math.min(img.naturalWidth-x,d.w/tr.scale),h=Math.min(img.naturalHeight-y,d.h/tr.scale),idx=s.elements.length,cue=s.cues[Math.min(idx,s.cues.length-1)],start=cue?.startMs??idx*1200,dur=Math.max(600,(cue?.endMs??start+1800)-start);s.elements.push({id:`element-${idx+1}`,label:`요소 ${idx+1}`,sequence:idx+1,narrativeRole:"",subtitle:cue?.text||"",type:"illustration",region:{x:Math.round(x),y:Math.round(y),width:Math.round(w),height:Math.round(h)},reveal:{direction:"left_to_right",startMs:Math.round(start),durationMs:Math.round(dur),maskPaddingPx:12,protectedRegions:[]},handPath:{start:[Math.round(x),Math.round(y+h/2)],end:[Math.round(x+w),Math.round(y+h/2)],easing:"easeInOut"},colorPhase:72});state.elementIndex=s.elements.length-1;renderElementList();updateInspector();renderSceneList();draw()});
function stopPlayback(){state.playing=false;state.projectPlaying=false;cancelAnimationFrame(state.raf);state.lastTick=0;if($("#playBtn"))$("#playBtn").textContent="▶ 장면";if($("#playProjectBtn"))$("#playProjectBtn").textContent="▶ 전체"}
function playLoop(ts){if(!state.playing)return;if(!state.lastTick)state.lastTick=ts;state.timeMs+=ts-state.lastTick;state.lastTick=ts;const s=currentScene(),dur=(s?.durationMs||0)+ +$("#holdMs").value;if(state.timeMs>=dur){state.timeMs=dur;stopPlayback();draw();return}draw();state.raf=requestAnimationFrame(playLoop)}
function togglePlay(){const s=currentScene();if(!s)return;if(state.playing){stopPlayback();draw()}else{stopPlayback();if(state.timeMs>=s.durationMs+ +$("#holdMs").value)state.timeMs=0;state.playing=true;$("#playBtn").textContent="Ⅱ 일시정지";state.raf=requestAnimationFrame(playLoop)}}
async function playAll(){if(!state.scenes.length)return;stopPlayback();state.projectPlaying=true;$("#playProjectBtn").textContent="Ⅱ 전체 재생 중";for(let i=0;i<state.scenes.length&&state.projectPlaying;i++){state.sceneIndex=i;state.elementIndex=-1;renderSceneList();renderPromptSceneList();updateInspector();await ensureSceneImage(currentScene());const dur=currentScene().durationMs+ +$("#holdMs").value,start=performance.now();await new Promise(resolve=>{function tick(now){if(!state.projectPlaying){resolve();return}state.timeMs=Math.min(dur,now-start);draw();if(now-start<dur)requestAnimationFrame(tick);else resolve()}requestAnimationFrame(tick)})}stopPlayback();draw()}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},300)}function downloadText(t,n,type="application/json"){downloadBlob(new Blob([t],{type}),n)}
async function recordSequence(all=false){
  const scenes=all?state.scenes:[currentScene()].filter(Boolean);if(!scenes.length||!scenes.some(s=>s.imageData)){toast("이미지가 있는 장면이 필요합니다.");return}
  if(!canvas.captureStream||!window.MediaRecorder){toast("이 브라우저는 WebM 내보내기를 지원하지 않습니다.");return}
  stopPlayback();const fps=clamp(+$("#fps").value||30,12,60),stream=canvas.captureStream(fps),types=["video/webm;codecs=vp9","video/webm;codecs=vp8","video/webm"],mime=types.find(MediaRecorder.isTypeSupported)||"",rec=new MediaRecorder(stream,mime?{mimeType:mime}:{}),chunks=[];
  const btn=all?$("#recordProjectBtn"):$("#recordBtn"),status=$("#exportStatus"),statusText=$("#exportStatusText"),detail=$("#exportStatusDetail"),progress=$("#exportProgress");
  const oldIndex=state.sceneIndex,oldTime=state.timeMs,total=scenes.reduce((sum,s)=>sum+s.durationMs+ +$("#holdMs").value,0);let completed=0;
  const update=(pct,label)=>{if(status)status.classList.remove('hidden');if(statusText)statusText.textContent=label;if(detail)detail.textContent=`${Math.round(pct)}%`;if(progress)progress.value=pct};
  rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};btn.disabled=true;update(0,all?'전체 WebM 내보내는 중':'장면 WebM 내보내는 중');rec.start();
  for(const s of scenes){state.sceneIndex=state.scenes.indexOf(s);renderSceneList();renderPromptSceneList();await ensureSceneImage(s);const dur=s.durationMs+ +$("#holdMs").value,start=performance.now();await new Promise(resolve=>{function tick(now){state.timeMs=Math.min(dur,now-start);update((completed+state.timeMs)/total*100,all?'전체 WebM 내보내는 중':'장면 WebM 내보내는 중');draw();if(now-start<dur)requestAnimationFrame(tick);else resolve()}requestAnimationFrame(tick)});completed+=dur}
  await sleep(80);const stopped=new Promise(r=>rec.onstop=r);rec.stop();await stopped;downloadBlob(new Blob(chunks,{type:rec.mimeType||"video/webm"}),all?`${state.projectName}-full.webm`:`${scenes[0]?.id||"scene"}.webm`);btn.disabled=false;update(100,'WebM 저장 완료');
  if(oldIndex>=0){state.sceneIndex=oldIndex;state.timeMs=oldTime;renderSceneList();renderPromptSceneList();updateInspector()}draw();setTimeout(()=>status?.classList.add('hidden'),1200)
}
function safeProject(){return{format:"whiteboard-ai-motion-studio/v4",projectName:state.projectName,builder:{script:$("#scriptInput")?.value||"",srt:$("#srtBuilderOutput")?.value||$("#srtInput")?.value||""},cues:state.cues,scenes:state.scenes.map(({_img,...s})=>s),output:{width:+$("#outWidth").value,height:+$("#outHeight").value,fps:+$("#fps").value,holdMs:+$("#holdMs").value,paperColor:paper(),burnSubtitles:$("#burnSubtitles").checked}}}
function exportAnnotation(){const s=currentScene();if(!s)return;downloadText(JSON.stringify({sceneId:s.id,canvas:{width:s.imageWidth,height:s.imageHeight},storyBasis:s.cues.map(c=>c.text).join(" "),sceneDurationMs:s.durationMs,elements:s.elements.map((e,i)=>({...e,sequence:i+1}))},null,2),`${s.id}.annotation.json`)}
function exportHyperFrames(){const s=currentScene();if(!s?.imageData){toast("이미지가 있는 장면을 선택하세요.");return}const W=+$("#outWidth").value,H=+$("#outHeight").value,duration=(s.durationMs+ +$("#holdMs").value)/1000,layers=s.elements.map((e,i)=>{const r=e.region,st=e.reveal.startMs/1000,du=e.reveal.durationMs/1000;return `<div class="clip layer" data-start="${st}" data-duration="${du}" data-track-index="${i}" style="left:${r.x/s.imageWidth*100}%;top:${r.y/s.imageHeight*100}%;width:${r.width/s.imageWidth*100}%;height:${r.height/s.imageHeight*100}%;overflow:hidden"><img src="${s.imageData}" style="position:absolute;width:${s.imageWidth/r.width*100}%;height:${s.imageHeight/r.height*100}%;left:${-r.x/r.width*100}%;top:${-r.y/r.height*100}%"></div>`}).join("\n"),anims=s.elements.map((e,i)=>{const st=e.reveal.startMs/1000,du=e.reveal.durationMs/1000,d=e.reveal.direction,from=d==="right_to_left"?"inset(0 0 0 100%)":d==="top_to_bottom"?"inset(0 0 100% 0)":d==="bottom_to_top"?"inset(100% 0 0 0)":d==="center_out"?"inset(50% 50% 50% 50%)":"inset(0 100% 0 0)";return `tl.fromTo(layers[${i}],{clipPath:"${from}"},{clipPath:"inset(0 0 0 0)",duration:${du},ease:"none"},${st});`}).join("\n");const html=`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:${paper()};display:grid;place-items:center;height:100%}.stage{position:relative;width:${W}px;height:${H}px;background:${paper()};overflow:hidden}.layer{position:absolute}.layer img{display:block;max-width:none}</style></head><body><div id="stage" class="stage" data-composition-id="${s.id}" data-start="0" data-duration="${duration}" data-width="${W}" data-height="${H}">${layers}</div><script src="https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js"><\/script><script>const layers=[...document.querySelectorAll('.layer')];const tl=gsap.timeline({paused:true});${anims}window.__timelines=window.__timelines||{};window.__timelines['${s.id}']=tl;<\/script></body></html>`;downloadText(html,`${s.id}-hyperframes.html`,"text/html")}

function showTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tabview').forEach(v=>v.classList.toggle('active',v.id===`tab-${name}`));if(name==='prompt'){renderPromptSceneList();syncPromptEditor()}window.scrollTo({top:0,behavior:'smooth'})}
$$('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.go));

function srtPrompt(){const script=$("#scriptInput").value.trim(),max=+$("#captionChars").value||28,min=+$("#captionMinSec").value||1.3,maxSec=+$("#captionMaxSec").value||4.5,total=state.mediaDuration?`전체 미디어 길이는 약 ${state.mediaDuration.toFixed(1)}초입니다. 가능한 한 마지막 자막 종료 시간을 여기에 맞추세요.`:"";return `다음 한국어 내레이션을 표준 SRT 자막으로 변환하세요.\n\n규칙:\n- 답변에는 SRT 본문만 출력하고 설명/마크다운 코드블록은 금지\n- 자막 번호는 1부터 연속\n- 시간 형식 HH:MM:SS,mmm --> HH:MM:SS,mmm\n- 한 자막은 가능하면 ${max}자 이하\n- 한 자막 표시 시간은 대략 ${min}~${maxSec}초\n- 문장을 의미 단위로 나누고 조사/수식어만 홀로 남기지 않기\n- 앞뒤 자막 시간이 겹치지 않기\n- 원문의 의미를 추가하거나 삭제하지 않기\n${total}\n\n원문:\n${script}`}
function syncSrtToBuilder(t){$("#srtBuilderOutput").value=extractSrt(t);$("#srtValidation").className="validation neutral";$("#srtValidation").textContent="SRT가 입력되었습니다. 검사 버튼으로 확인하세요."}

const externalUrls={chatgpt:"https://chatgpt.com/",gemini:"https://gemini.google.com/",claude:"https://claude.ai/",grok:"https://grok.com/"};
async function copyText(t){try{await navigator.clipboard.writeText(t);toast("클립보드에 복사했습니다.")}catch{toast("복사 권한이 없어 직접 선택해 주세요.")}}
function getSettings(){let s={};try{s=JSON.parse(localStorage.getItem('wai-settings')||'{}')}catch{}return s}
function saveSettings(){const models={};for(const p of ['openai','gemini','anthropic','xai'])models[p]={text:$(`#model-${p}-text`)?.value||'',image:$(`#model-${p}-image`)?.value||''};const cfg={gatewayUrl:$("#gatewayUrl").value.trim().replace(/\/$/,''),models};localStorage.setItem('wai-settings',JSON.stringify(cfg));sessionStorage.setItem('wai-gateway-token',$("#gatewayToken").value);refreshGatewayStatus();syncImageProviderModel();toast("API 연결 설정을 저장했습니다.")}
function loadSettings(){const s=getSettings();$("#gatewayUrl").value=s.gatewayUrl||'';$("#gatewayToken").value=sessionStorage.getItem('wai-gateway-token')||'';for(const p of ['openai','gemini','anthropic','xai']){const m=s.models?.[p]||defaults.models[p];if($(`#model-${p}-text`))$(`#model-${p}-text`).value=m.text||defaults.models[p].text;if($(`#model-${p}-image`))$(`#model-${p}-image`).value=m.image||defaults.models[p].image}refreshGatewayStatus();syncImageProviderModel()}
function modelFor(provider,type='text'){return $(`#model-${provider}-${type}`)?.value||getSettings().models?.[provider]?.[type]||defaults.models[provider]?.[type]||''}
function gatewayConfig(){return{url:$("#gatewayUrl").value.trim().replace(/\/$/,''),token:$("#gatewayToken").value||sessionStorage.getItem('wai-gateway-token')||''}}
function refreshGatewayStatus(mode){const e=$("#gatewayStatus"),g=gatewayConfig();if(mode===true){e.className="status-dot on";e.textContent="Gateway 연결됨"}else if(mode===false){e.className="status-dot bad";e.textContent="Gateway 오류"}else if(g.url){e.className="status-dot";e.textContent="Gateway 설정됨"}else{e.className="status-dot off";e.textContent="Gateway 미연결"}}
async function gatewayFetch(path,options={}){const g=gatewayConfig();if(!g.url)throw new Error('API 연결 탭에서 Gateway URL을 먼저 설정하세요.');const headers=new Headers(options.headers||{});if(g.token)headers.set('X-Gateway-Token',g.token);const r=await fetch(g.url+path,{...options,headers});const txt=await r.text();let data;try{data=JSON.parse(txt)}catch{data={error:txt||r.statusText}}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function aiText(provider,system,prompt){const model=modelFor(provider,'text');const d=await gatewayFetch('/v1/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,model,system,prompt})});return d.text||''}

function sceneNarrativeText(s){return(s?.cues||[]).map(c=>c.text).join(' ')}
const presetRules={whiteboard:'Educational whiteboard illustration on warm cream paper, clean black hand-drawn ink lines, restrained flat accent colors, clear semantic groups, generous negative space, easy to reveal region by region.',infographic:'Clean editorial infographic with one strong visual hierarchy, 3–5 large semantic groups, minimal arrows, consistent icons, flat colors, high legibility.',story:'Cohesive storybook editorial illustration, expressive but simple characters, clear staging, consistent character appearance, uncluttered background, strong focal action.',technical:'Precise technical explanatory diagram, simplified components, clear spatial relationships, orthographic or cutaway view when useful, minimal labels, engineering clarity.',product:'Premium product explainer scene, product as the dominant focal object, clean contextual props, controlled lighting, simple composition, enough negative space for callouts.'};
function makeScenePrompt(s){if(!s)return'';const preset=$("#promptPreset").value,aspect=$("#promptAspect").value,textPolicy=$("#promptTextPolicy").value,anchor=$("#styleAnchor").value.trim(),narrative=$("#sceneNarrative").value.trim()||sceneNarrativeText(s),policy=textPolicy==='none'?'Do not render any text, letters, captions, logos, watermarks, UI, or labels.':textPolicy==='minimal'?'Use text only if a single essential keyword is impossible to communicate visually; otherwise no text.':'Text is allowed only when it improves comprehension and must remain minimal.';return `${aspect} scene for a narrated explainer video.\n\nVisual direction: ${presetRules[preset]}\n${policy}\n\nScene meaning to visualize:\n${narrative}\n\nContinuity requirements:\n${anchor||'Keep line weight, palette, character design, camera language, and background treatment consistent with the other scenes.'}\n\nComposition requirements:\n- One obvious focal point and a readable left-to-right or center-out visual flow.\n- Separate major semantic objects with enough space so they can be revealed independently in animation.\n- Avoid decorative filler, dense patterns, tiny details, frames, mock UI, and unnecessary text.\n- Keep important content inside safe margins.\n- Produce a complete final illustration, not a storyboard sheet or collage of alternatives.`}
function syncPromptEditor(){const s=currentScene();$("#sceneNarrative").value=s?sceneNarrativeText(s):'';$("#scenePromptOutput").value=s?.prompt||'';if(s?.imageData){$("#generatedImagePreview").src=s.imageData;$("#generatedImagePreview").classList.add('show');$("#applyGeneratedImageBtn").disabled=false}else{$("#generatedImagePreview").classList.remove('show');$("#applyGeneratedImageBtn").disabled=true}syncImageProviderModel()}
function syncImageProviderModel(){const p=$("#imageProvider")?.value||'openai';if($("#imageModel"))$("#imageModel").value=modelFor(p,'image')}

$("#srtFile").onchange=async e=>{const f=e.target.files[0];if(f)$("#srtInput").value=await f.text()};$("#parseBtn").onclick=()=>{if(buildScenesFromSrt($("#srtInput").value)){toast(`${state.cues.length}개 자막 → ${state.scenes.length}개 장면`);showTab('studio')}};$("#addSceneBtn").onclick=()=>{state.scenes.push(makeScene([],state.scenes.length));selectScene(state.scenes.length-1)};$("#imageFile").onchange=e=>{const f=e.target.files[0];if(f)loadImageFile(f)};$("#promptImageFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;state.generatedImageData=await fileToDataURL(f);$("#generatedImagePreview").src=state.generatedImageData;$("#generatedImagePreview").classList.add('show');$("#applyGeneratedImageBtn").disabled=false};$("#addRegionBtn").onclick=()=>{if(!currentScene()?.imageData){toast("먼저 장면 이미지를 추가하세요.");return}state.drawMode=!state.drawMode;$("#addRegionBtn").textContent=state.drawMode?"그리기 취소":"영역 그리기"};$("#fullRegionBtn").onclick=addFullRegion;$("#playBtn").onclick=togglePlay;$("#playProjectBtn").onclick=playAll;$("#stopBtn").onclick=()=>{stopPlayback();draw()};$("#recordBtn").onclick=()=>recordSequence(false);$("#recordProjectBtn").onclick=()=>recordSequence(true);$("#scrubber").oninput=e=>{const s=currentScene();if(!s)return;stopPlayback();state.timeMs=(s.durationMs+ +$("#holdMs").value)*(+e.target.value/1000);draw()};["outWidth","outHeight"].forEach(id=>$("#"+id).onchange=()=>{updateCanvasSize();draw()});["holdMs","paperColor","burnSubtitles"].forEach(id=>$("#"+id).oninput=()=>draw());$("#openPromptBtn").onclick=()=>showTab('prompt');
function bindInput(id,fn,event='input'){$("#"+id).addEventListener(event,()=>{const e=currentElement();if(!e)return;fn(e);renderElementList();draw()})}bindInput('elLabel',e=>e.label=$("#elLabel").value);bindInput('elRole',e=>e.narrativeRole=$("#elRole").value);bindInput('elStart',e=>e.reveal.startMs=+$("#elStart").value||0);bindInput('elDuration',e=>e.reveal.durationMs=Math.max(100,+$("#elDuration").value||100));bindInput('elDirection',e=>e.reveal.direction=$("#elDirection").value,'change');bindInput('elPadding',e=>e.reveal.maskPaddingPx=+$("#elPadding").value||0);bindInput('elColorPhase',e=>e.colorPhase=clamp(+$("#elColorPhase").value||0,0,100));bindInput('elSubtitle',e=>{const s=currentScene(),c=s.cues[+$("#elSubtitle").value];e.subtitle=c?.text||''},'change');$("#moveUpBtn").onclick=()=>{const s=currentScene(),i=state.elementIndex;if(!s||i<=0)return;[s.elements[i-1],s.elements[i]]=[s.elements[i],s.elements[i-1]];state.elementIndex--;renderElementList();draw()};$("#moveDownBtn").onclick=()=>{const s=currentScene(),i=state.elementIndex;if(!s||i<0||i>=s.elements.length-1)return;[s.elements[i+1],s.elements[i]]=[s.elements[i],s.elements[i+1]];state.elementIndex++;renderElementList();draw()};$("#deleteElementBtn").onclick=()=>{const s=currentScene(),i=state.elementIndex;if(!s||i<0)return;s.elements.splice(i,1);state.elementIndex=Math.min(i,s.elements.length-1);renderElementList();updateInspector();renderSceneList();draw()};$("#exportAnnotationBtn").onclick=exportAnnotation;$("#exportProjectBtn").onclick=()=>downloadText(JSON.stringify(safeProject(),null,2),`${state.projectName}.json`);$("#exportHFBtn").onclick=exportHyperFrames;
$("#projectFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());state.projectName=p.projectName||'whiteboard-ai-project';state.cues=p.cues||[];state.scenes=p.scenes||[];const o=p.output||{};if(o.width)$("#outWidth").value=o.width;if(o.height)$("#outHeight").value=o.height;if(o.fps)$("#fps").value=o.fps;if(o.holdMs!=null)$("#holdMs").value=o.holdMs;if(o.paperColor)$("#paperColor").value=o.paperColor;if(o.burnSubtitles!=null)$("#burnSubtitles").checked=o.burnSubtitles;selectScene(state.scenes.length?0:-1);toast('프로젝트를 불러왔습니다.')}catch{toast('프로젝트 JSON을 읽지 못했습니다.')}};

$("#localSrtBtn").onclick=()=>syncSrtToBuilder(localSrtFromText($("#scriptInput").value,state.mediaDuration));$("#makeSrtPromptBtn").onclick=()=>{$("#srtPromptOutput").value=srtPrompt();toast('AI용 SRT 프롬프트를 만들었습니다.')};$("#copySrtPromptBtn").onclick=()=>copyText($("#srtPromptOutput").value||srtPrompt());$("#openExternalAiBtn").onclick=()=>{const p=$("#externalAiSelect").value;copyText($("#srtPromptOutput").value||srtPrompt());window.open(externalUrls[p],'_blank','noopener')};$("#useExternalSrtBtn").onclick=()=>syncSrtToBuilder($("#externalSrtResult").value);$("#aiSrtBtn").onclick=async()=>{const provider=$("#externalAiSelect").value==='chatgpt'?'openai':$("#externalAiSelect").value==='claude'?'anthropic':$("#externalAiSelect").value;try{$("#aiSrtBtn").disabled=true;$("#aiSrtBtn").textContent='AI 생성 중…';const out=await aiText(provider,'You are a professional subtitle editor. Return only valid SRT text.',srtPrompt());syncSrtToBuilder(out);toast('AI가 SRT를 생성했습니다.')}catch(e){toast(e.message)}finally{$("#aiSrtBtn").disabled=false;$("#aiSrtBtn").textContent='연결된 AI로 SRT 생성'}};$("#validateSrtBtn").onclick=()=>{const v=validateSrt($("#srtBuilderOutput").value),box=$("#srtValidation");box.className='validation '+(v.ok?'ok':'warn');box.textContent=v.ok?`정상: ${v.cues.length}개 자막, ${(v.cues.at(-1).endMs/1000).toFixed(1)}초`:`문제 ${v.issues.length}개: ${v.issues.slice(0,4).join(' / ')}`};$("#normalizeSrtBtn").onclick=()=>{syncSrtToBuilder(normalizeSrt($("#srtBuilderOutput").value));toast('번호와 시간 형식을 정리했습니다.')};$("#downloadSrtBtn").onclick=()=>downloadText($("#srtBuilderOutput").value,`${state.projectName}.srt`,'application/x-subrip');function applyBuilder(){const t=$("#srtBuilderOutput").value;if(!parseSRT(t).length){toast('먼저 SRT를 생성하세요.');return}$("#srtInput").value=t;if(buildScenesFromSrt(t)){showTab('studio');toast('SRT를 적용하고 장면을 만들었습니다.')}}$("#builderToStudioBtn").onclick=applyBuilder;$("#applySrtToStudioBtn").onclick=applyBuilder;
$("#mediaForTranscription").onchange=e=>{const f=e.target.files[0];if(!f)return;state.mediaFile=f;const url=URL.createObjectURL(f),m=document.createElement(f.type.startsWith('video')?'video':'audio');m.preload='metadata';m.onloadedmetadata=()=>{state.mediaDuration=isFinite(m.duration)?m.duration:0;$("#mediaInfo").textContent=`${f.name} · ${(f.size/1024/1024).toFixed(1)}MB · ${state.mediaDuration?state.mediaDuration.toFixed(1)+'초':'길이 확인 불가'}`;URL.revokeObjectURL(url)};m.src=url};$("#transcribeBtn").onclick=async()=>{if(!state.mediaFile){toast('먼저 음성/영상 파일을 선택하세요.');return}try{const f=new FormData();f.append('file',state.mediaFile);f.append('model',$("#transcribeModel").value.trim()||'whisper-1');f.append('language',$("#transcribeLanguage").value.trim());$("#transcribeBtn").disabled=true;$("#transcribeBtn").textContent='전사 중…';const d=await gatewayFetch('/v1/transcribe',{method:'POST',body:f});syncSrtToBuilder(d.srt||localSrtFromText(d.text||'',state.mediaDuration));if(d.text&&!$("#scriptInput").value)$("#scriptInput").value=d.text;toast('전사를 완료했습니다.')}catch(e){toast(e.message)}finally{$("#transcribeBtn").disabled=false;$("#transcribeBtn").textContent='전사 API로 SRT 만들기'}};

$("#generatePromptBtn").onclick=()=>{const s=currentScene();if(!s){toast('먼저 SRT로 장면을 만드세요.');return}s.prompt=makeScenePrompt(s);$("#scenePromptOutput").value=s.prompt;renderPromptSceneList()};$("#prepareAllPromptsBtn").onclick=()=>{if(!state.scenes.length){toast('먼저 SRT로 장면을 만드세요.');return}const cur=state.sceneIndex;state.scenes.forEach((s,i)=>{state.sceneIndex=i;$("#sceneNarrative").value=sceneNarrativeText(s);s.prompt=makeScenePrompt(s)});state.sceneIndex=cur>=0?cur:0;syncPromptEditor();renderPromptSceneList();toast(`${state.scenes.length}개 장면 프롬프트를 준비했습니다.`)};$("#copyScenePromptBtn").onclick=()=>copyText($("#scenePromptOutput").value);$("#refinePromptBtn").onclick=async()=>{const s=currentScene();if(!s)return;const provider=$("#externalAiSelect").value==='chatgpt'?'openai':$("#externalAiSelect").value==='claude'?'anthropic':$("#externalAiSelect").value;try{const base=$("#scenePromptOutput").value||makeScenePrompt(s),out=await aiText(provider,'You are a senior visual prompt designer. Improve the supplied image prompt while preserving all constraints. Return only the final prompt.',base);s.prompt=out;$("#scenePromptOutput").value=out;renderPromptSceneList();toast('프롬프트를 개선했습니다.')}catch(e){toast(e.message)}};$("#openImageAiBtn").onclick=()=>{const p=$("#externalAiSelect").value;copyText($("#scenePromptOutput").value||makeScenePrompt(currentScene()));window.open(externalUrls[p],'_blank','noopener')};$("#promptPreset").onchange=()=>{};$("#imageProvider").onchange=syncImageProviderModel;$("#generateImageBtn").onclick=async()=>{const s=currentScene();if(!s){toast('먼저 장면을 선택하세요.');return}const prompt=$("#scenePromptOutput").value||makeScenePrompt(s),provider=$("#imageProvider").value,model=$("#imageModel").value.trim()||modelFor(provider,'image'),box=$("#imageJobStatus");try{box.className='validation neutral';box.textContent=`${provider} 이미지 생성 요청 중…`;$("#generateImageBtn").disabled=true;const d=await gatewayFetch('/v1/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,model,prompt,size:$("#imageSize").value.trim()})});if(!d.dataUrl)throw new Error('Gateway가 이미지 데이터를 반환하지 않았습니다.');state.generatedImageData=d.dataUrl;$("#generatedImagePreview").src=d.dataUrl;$("#generatedImagePreview").classList.add('show');$("#applyGeneratedImageBtn").disabled=false;box.className='validation ok';box.textContent=`생성 완료 · ${provider} / ${model}`;toast('이미지를 생성했습니다.')}catch(e){box.className='validation bad';box.textContent=e.message;toast(e.message)}finally{$("#generateImageBtn").disabled=false}};$("#applyGeneratedImageBtn").onclick=async()=>{if(!state.generatedImageData)return;await setSceneImageData(state.generatedImageData,'ai-generated.png');showTab('studio')};

$("#saveGatewayBtn").onclick=saveSettings;$("#clearGatewayTokenBtn").onclick=()=>{$("#gatewayToken").value='';sessionStorage.removeItem('wai-gateway-token');refreshGatewayStatus();toast('Gateway 세션 토큰을 지웠습니다.')};$("#checkGatewayBtn").onclick=async()=>{try{const d=await gatewayFetch('/health');refreshGatewayStatus(true);toast(d.message||'Gateway가 응답했습니다.')}catch(e){refreshGatewayStatus(false);toast(e.message)}};$$('.provider-test').forEach(b=>b.onclick=async()=>{saveSettings();const p=b.dataset.provider,res=$(`#test-${p}`);res.textContent='테스트 중…';try{const out=await aiText(p,'Reply with exactly: OK','Connection test. Reply OK.');res.textContent='성공: '+out.slice(0,100);refreshGatewayStatus(true)}catch(e){res.textContent='실패: '+e.message;refreshGatewayStatus(false)}});

$("#scriptInput").value=`AI를 활용한 화이트보드 영상 제작은 세 단계로 생각하면 쉽습니다. 먼저 대본을 자막으로 나누고, 다음으로 자막을 의미 단위 장면으로 묶습니다. 마지막으로 각 장면에 맞는 이미지를 만들고 순서대로 나타나게 하면 설명형 애니메이션이 완성됩니다.`;
loadSettings();updateCanvasSize();draw();
window.WhiteboardStudio={state,defaults,safeProject,selectScene,buildScenesFromSrt,renderSceneList,renderPromptSceneList,renderElementList,updateInspector,updateCanvasSize,draw,syncPromptEditor,showTab,gatewayFetch,saveSettings,loadSettings,modelFor,toast,parseSRT,cuesToSrt,makeScenePrompt,setSceneImageData,loadImageFile,stopPlayback};
})();